/*
 * Aplicacion del hash SHA-1
 */
package sha;

import java.awt.Color;
import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ivan Garcia Miranda y Alvaro Alonso Isla
 */
public class Sha1 extends javax.swing.JFrame {

    //Variables de la interfaz para almacenar los tetos
    String mensajeOriginal = "";
    byte[] mensajeOrignBytes = null;
    String hashSha = "";
    String hashShaJava = "";
    byte[] hashedBytes = null;

    /**
     * Creates new form sha1
     */
    public Sha1() {
        //Inicializamos la interfaz
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Txt_Mensaje = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Txt_hash = new javax.swing.JTextField();
        Btn_Calcular = new javax.swing.JButton();
        Btn_Borrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Txt_hashJava = new javax.swing.JTextField();
        Txt_Infor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SHA-1");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        Txt_Mensaje.setColumns(20);
        Txt_Mensaje.setRows(5);
        Txt_Mensaje.setName(""); // NOI18N
        jScrollPane1.setViewportView(Txt_Mensaje);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel1.setText("Menaje original");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Hash SHA-1 Calculado");

        Txt_hash.setEditable(false);
        Txt_hash.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        Txt_hash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_hashActionPerformed(evt);
            }
        });

        Btn_Calcular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_Calcular.setText("Calcular Hash");
        Btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CalcularActionPerformed(evt);
            }
        });

        Btn_Borrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Btn_Borrar.setText("Borrar");
        Btn_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BorrarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Hash SHA-1 Calculado Java");

        Txt_hashJava.setEditable(false);
        Txt_hashJava.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        Txt_Infor.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("Develop by: Alvaro Alonso & Ivan Garcia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txt_hash)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Btn_Borrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_Calcular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addComponent(Txt_Infor, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(Txt_hashJava))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_hash, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_hashJava, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Calcular)
                    .addComponent(Txt_Infor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Borrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_hashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_hashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_hashActionPerformed
//evento que ocurre al pulsar el boton borrar
    private void Btn_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BorrarActionPerformed
        //Borramos y restablecemos la interfaz
        Txt_Mensaje.setText("");
        Txt_hash.setText("");
        Txt_hashJava.setText("");
        Txt_Infor.setText("");
        Txt_hashJava.setBackground(Color.white);
        Txt_hash.setBackground(Color.white);
        Txt_Mensaje.enable();

    }//GEN-LAST:event_Btn_BorrarActionPerformed
//evento que ocurre al pulsar el boton calcular
    private void Btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CalcularActionPerformed
        // Instanciamos la clase CalculaHash
        CalculaHash hash = new CalculaHash();
        //comprobamos que existe un mensaje
        if (Txt_Mensaje.getText().compareTo("") != 0) {

            Txt_Mensaje.disable();
            mensajeOriginal = Txt_Mensaje.getText();
            Txt_Mensaje.setText("");
            try {
                //Extraemos los bytes del mensaje en una codificacion UTF-8
                mensajeOrignBytes = (mensajeOriginal).getBytes("UTF-8");
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(Sha1.class.getName()).log(Level.SEVERE, null, ex);
            }
            //Llamamos al metodo calcular pasando como parametro el array de bytes
            hashSha = hash.calcular(mensajeOrignBytes);

            try {
                //Calculamos el hash mediante la libreria de java
                //esto se realiza para hacer una comparativa entre el neustor y el de java
                //Instanciamos un messageDigest del tipo SHA-1
                MessageDigest digest = MessageDigest.getInstance("SHA-1");
                //Hacemos el hash
                hashedBytes = digest.digest(mensajeOrignBytes);
                //Convertimo a un string hexadecimal
                hashShaJava = convertByteArrayToHexString(hashedBytes);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(Sha1.class.getName()).log(Level.SEVERE, null, ex);
            }
            //Si ambos hash coinciden, es todo correcto
            if (hashSha.compareTo(hashShaJava) == 0) {
                Txt_hashJava.setBackground(Color.green);
                Txt_hash.setBackground(Color.green);
                Txt_Infor.setText("El codigo hash calculado es correcto");
            } else 
            //Los hash calculados no coinciden
            {
                Txt_hashJava.setBackground(Color.red);
                Txt_hash.setBackground(Color.red);
                Txt_Infor.setText("Ups! Parece que uno de los hash es incorrecto!!");
                Txt_Infor.setForeground(Color.red);
            }

            Txt_hashJava.setText(hashShaJava);
            Txt_hash.setText(hashSha);
        } else 
        //No se ha introducido ningun mensaje
        {
            Txt_Infor.setText("No has introducido ningun dato");

        }
    }//GEN-LAST:event_Btn_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sha1().setVisible(true);
            }
        });

    }

    private static String convertByteArrayToHexString(byte[] arrayBytes) {
        StringBuffer stringBuffer = new StringBuffer();
        for (int i = 0; i < arrayBytes.length; i++) {
            stringBuffer.append(Integer.toString((arrayBytes[i] & 0xff) + 0x100, 16)
                    .substring(1));
        }
        return stringBuffer.toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Borrar;
    private javax.swing.JButton Btn_Calcular;
    private javax.swing.JLabel Txt_Infor;
    private javax.swing.JTextArea Txt_Mensaje;
    private javax.swing.JTextField Txt_hash;
    private javax.swing.JTextField Txt_hashJava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
